### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by semarco** [basho-labs/vagrant-riak-cs-cluster#5]
hi, sorry if I missed something but I cannot start the cluster (vagrant 1.1.4)

[riak1] Setting hostname...
[riak1] Configuring and enabling network interfaces...
[riak1] Mounting shared folders...
[riak1] -- /vagrant
[riak1] -- /tmp/vagrant-chef-1/lib
[riak1] -- /tmp/vagrant-chef-1/chef-solo-2/roles
[riak1] -- /tmp/vagrant-chef-1/chef-solo-1/cookbooks
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` v-csc-1 /tmp/vagrant-chef-1/chef-solo-1/cookbooks

**Comment by hectcastro** [comment]
This is usually caused because the local `cookbooks` directory does not exist. Not sure how you updated to the codebase on `master`, but a fresh clone of the repository should work. If not, can you please provide the steps that occurred before running `vagrant up`? Also, potentially the output of `git --version` and your operating system?

**Comment by semarco** [comment]
It seems that I was on the wrong 1.1 branch.
The master works fine with Vagrant 1.1.4.
Cluster is up and running, thanks a lot!!! :-)
